name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with Maven
        run: |
          ./mvnw -B -DskipTests verify

      - name: Build image with Buildpacks (paketo)
        run: |
          ./mvnw -B -DskipTests spring-boot:build-image
