name: Octopus deploy

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: {}
  # Run automatically after the CI workflow completes successfully on the main branch
  workflow_run:
    workflows: ["RTM Sample App CI"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    # Only run this job automatically when the triggering workflow (CI) completed successfully
    # For manual workflow_dispatch this job will still run.
    if: github.event_name != 'workflow_run' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main')
    env:
      # Octopus project slug configurable via repo variable (set in Settings > Variables)
      OCTOPUS_PROJECT_SLUG: ${{ secrets.OCTOPUS_PROJECT_SLUG }}
    outputs:
      version: ${{ steps.get-version.outputs.payload_version }}
      package_id: ${{ steps.get-artifact-id.outputs.package_id }}
      group_id: ${{ steps.get-group-id.outputs.group_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact from triggering CI run
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v5
        with:
          name: octopus-payload
          # Run id of the triggering workflow_run event
          run-id: ${{ github.event.workflow_run.id }}
          path: octopus-payload
          repository: ${{ github.repository }}
          github-token: ${{ secrets.RTM_TEST }}

      - name: Read octopus payload file
        id: read-payload
        uses: guibranco/github-file-reader-action-v2@v2.2.854
        with:
          path: ${{ github.workspace }}/octopus-payload/octopus_payload.json

      - name: Get project version
        id: get-version
        run: |
          set -euo pipefail
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout || true)
          echo "payload_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get artifact id
        id: get-artifact-id
        run: |
          set -euo pipefail
          ARTIFACT_ID=$(./mvnw help:evaluate -Dexpression=project.artifactId -q -DforceStdout || true)
          echo "package_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT

      - name: Get group id
        id: get-group-id
        run: |
          set -euo pipefail
          GROUP_ID=$(./mvnw help:evaluate -Dexpression=project.groupId -q -DforceStdout || true)
          echo "group_id=$GROUP_ID" >> $GITHUB_OUTPUT
    

      - name: Create a Zip package
        uses: OctopusDeploy/create-zip-package-action@v3
        with:
          package_id: ${{ steps.get-artifact-id.outputs.package_id }}
          version: ${{ steps.get-version.outputs.payload_version }}
          output_folder: ${{ github.workspace }}/artifacts
          base_path: ${{ github.workspace }}/octopus-payload
          files: '**/*'

      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: 'latest'

      - name: Publish Artifacts to Octopus
        uses: OctopusDeploy/push-package-action@v3
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE }}
        with: 
          packages: |
            ${{ github.workspace }}/artifacts/${{ steps.get-artifact-id.outputs.package_id }}.${{ steps.get-version.outputs.payload_version }}.zip
          overwrite_mode: OverwriteExisting
          
      - name: Push Build Information
        uses: OctopusDeploy/push-build-information-action@v3
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE }}
        with:
          packages: |
            ${{ steps.get-artifact-id.outputs.package_id }}
          version: ${{ steps.get-version.outputs.payload_version }}
          overwrite_mode: OverwriteExisting

      - name: Create a release in Octopus Deploy
        id: create-release
        uses: OctopusDeploy/create-release-action@v3.3.0
        env:
          OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SPACE: ${{ vars.OCTOPUS_SPACE }}
        with:
          project: ${{ secrets.OCTOPUS_PROJECT_SLUG }}
          packages: |
            ${{ steps.get-artifact-id.outputs.package_id }}:${{ steps.get-version.outputs.payload_version }}